### ISSUE TITLE
Barometric Pressure Decimal Places

### ISSUE THREAD

**Issue by mwolter805** [briis/hass-weatherflow#11]
Hello,
Migrating from your WeatherFlow Smart Weather to the WeatherFlow Weather integration and noticed reduced accuracy for barometric pressure. Typically in the US, barometric pressure is reported as at least two and often three digits. Currently, it is only one.

**Comment by briis** [comment]
Thanks. I can certainly fix that. Are there any other of the values that need more decimals as to US standards?

**Comment by mwolter805** [comment]
These are the barometric pressure entities that should be adjusted to have two or three decimal places:
_barometric_pressure
_sea_level_pressure
_station_pressure

I believe everything else is fine.

Thank you!

**Comment by briis** [comment]
These are now changed to 3 decimals. Will be in the next release.

**Comment by mwolter805** [comment]
Found a couple more issues when comparing to the station page from Tempest (https://tempestwx.com). There appear to be calculation issues with Delta T and Air Density. Included barometric pressure so you can see the digits they display.

These are the values from the station page
![Screen Shot 2021-12-06 at 8 58 44 AM](https://user-images.githubusercontent.com/24851651/144888762-47c507ec-3f79-452d-9d69-186cd225a745.jpg)
![Screen Shot 2021-12-06 at 8 59 01 AM](https://user-images.githubusercontent.com/24851651/144888801-a075f24b-611a-4d2b-97ac-4e4bce05be45.jpg)
![Screen Shot 2021-12-06 at 8 59 10 AM](https://user-images.githubusercontent.com/24851651/144888839-9f84a831-846c-4096-b7c0-ddee21918fb1.jpg)

And this is from the integration
![Screen Shot 2021-12-06 at 9 06 07 AM](https://user-images.githubusercontent.com/24851651/144889931-95233eed-bd13-4d85-b0b4-a3399272be37.jpg)
![Screen Shot 2021-12-06 at 9 00 51 AM](https://user-images.githubusercontent.com/24851651/144889133-afbcbdb9-5874-4153-9bfe-df0ff2617b1d.jpg)
![Screen Shot 2021-12-06 at 9 01 19 AM](https://user-images.githubusercontent.com/24851651/144889212-e3ca2e9c-af20-4421-9003-15fdd3f4b2d3.jpg)

**Comment by briis** [comment]
Got it. Will look at these also.

**Comment by briis** [comment]
Released V0.1.12 which fixes this issue. Re-Open if it does not work.
