### ISSUE TITLE
Air Density to five decimal places

### ISSUE THREAD

**Issue by mwolter805** [briis/hass-weatherflow#13]
Hello, thank you for the recent changes of decimal places for barometric pressure. 

Can you do the same for Air Density and provide five decimal places? The current single decimal does not provide enough resolution.

From https://tempestwx.com
![Screen Shot 2021-12-07 at 8 19 16 AM](https://user-images.githubusercontent.com/24851651/145066317-612029e6-d19d-4e35-8cfe-578611675dda.jpg)
From the integration
![Screen Shot 2021-12-07 at 8 18 57 AM](https://user-images.githubusercontent.com/24851651/145066283-4e5fd407-aa3c-441a-88fc-a6a310596717.jpg)

Thank you!

**Comment by briis** [comment]
Absolutely. I will fix this right away, but just hold on for a day or two to see if something else pops up, before I release.

**Comment by briis** [comment]
Just released v0.1.13, which fixes this issue.
