### ISSUE TITLE
Unexpected error fetching weatherflow data: list index out of range

### ISSUE THREAD

**Issue by dhover** [briis/hass-weatherflow#14]
A small problem and hopefully easy to fix.
The battery of my Tempest weatherstation has died. Now the integration doesn't initialize.
```
2021-12-13 19:59:48 ERROR (MainThread) [custom_components.weatherflow] Unexpected error fetching weatherflow data: list index out of range
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/weatherflow/__init__.py", line 105, in async_update_data
data: ObservationDescription = await weatherflowapi.update_observations()
File "/usr/local/lib/python3.9/site-packages/pyweatherflowrest/api.py", line 183, in update_observations
obervations: dict = data['obs'][0]
IndexError: list index out of range
```

**Comment by briis** [comment]
Is the device up and running again? What would you have liked to happen? I can make a more graceful exit, but without any data, I cannot continue setting it up.

**Comment by briis** [comment]
I have now made a more graceful handling of this, and instead of a crash log you will not get a warning in the log file and on the Integration page you will get this image. It will retry the connection with some Interval.

Could that work?

<img width="507" alt="Skærmbillede 2021-12-14 kl  11 23 03" src="https://user-images.githubusercontent.com/24776272/145980397-dea37200-cec1-4817-9a45-4cc382f2483f.png">
:

**Comment by briis** [comment]
I pushed out release 0.1.14. Should be available in HACS with the next hour. 
Closing this issue.

**Comment by dhover** [comment]
> I have now made a more graceful handling of this, and instead of a crash log you will not get a warning in the log file and on the Integration page you will get this image. It will retry the connection with some Interval.
> 
> Could that work?
> 
> <img alt="Skærmbillede 2021-12-14 kl 11 23 03" width="507" src="https://user-images.githubusercontent.com/24776272/145980397-dea37200-cec1-4817-9a45-4cc382f2483f.png">
> 
> :

Yes that works fine. Thanks for that. Now I am waiting for the new Tempest station. It will be replaced!

One remark about the new integration:
I compared the sensors from the old smartweather integration and the new one. I found one sensor is missing e.g. "Station information". Did you do that on purpose?

**Comment by briis** [comment]
Glad that this worked for you.

> Now I am waiting for the new Tempest station. It will be replaced!

Hope you get it soon.

> "Station information". Did you do that on purpose?

Yes. But just to see if anyone actually noticed 😁. I wanted to clean out sensors that nobody used, and I was not sure if this was used by anyone. Can I ask you to create a new issue, where you want this sensor back?

**Comment by dhover** [comment]
> Yes. But just to see if anyone actually noticed 😁. I wanted to clean out sensors that nobody used, and I was not sure if this was used by anyone. Can I ask you to create a new issue, where you want this sensor back?

I don't need it. It was only a remark if you hadn't noticed it.

**Comment by briis** [comment]
I think I will do it anyway. Thanks.
