### ISSUE TITLE
Allow configuration of `hour_cnt` in `pyweatherflowrest` for `forecast_hourly`

### ISSUE THREAD

**Issue by csacca** [briis/hass-weatherflow#16]
I understand the reason for reducing the hourly forecast from 240 hours but it would still be nice to have more than 48 hours (at least to see what time of day the highs and lows are going to be, approximately). Would it be a reasonable compromise to allow the number of hours retrieved to be configurable?

**Comment by briis** [comment]
Good idea. I can do that.

**Comment by briis** [comment]
I released V0.1.16, where you now can configure the number of hours, from the CONFIGURE button, on the Integration page. Closing this issue.
