### ISSUE TITLE
Feature request: Add wind gust to hourly forecast 

### ISSUE THREAD

**Issue by GoPosi** [briis/hass-weatherflow#19]
Would it be possible to add the wind_gust forecast as an attribute under the hourly weather entity?  I currently get the values from a rest sensor I pull from my station, but doing so requires some complex template sensors that aren't exactly ideal. It would greatly simplify my setup if the values were part of the weather entity.

**Comment by briis** [comment]
Yes, this is possible. I will add it in as an attribute for the next version.

**Comment by briis** [comment]
I have now released V1.0.0 where this is added (Plus a few extra attributes 😁).
