### ISSUE TITLE
Can't find in integrations

### ISSUE THREAD

**Issue by donnievawter** [briis/hass-weatherflow#25]
I have added this through HACS and see it there and in custom components. However, even after clearing browser cache, when I go to configure/integrations it is not there and clicking on add integration it finds no integration starting with weatherf.  I have the old integration installed as a custom component. Is that screwing things up? No clue where to go next.

**Comment by briis** [comment]
Have you restarted home assistant?

If you have it is 99% a caching issue in your browser.

**Comment by alexbromberek2020** [comment]
I am getting this error 

Retrying setup: Error while retreiving data: Timeout fetching weatherflow data. and it was working fine like a week ago

**Comment by donnievawter** [comment]
Thanks,
I had cleared browser cache and restarted HA multiple times with no luck.
I finally used Safari which I seldom use and it showed up so likely a cache issue that didn’t clear in Edge. All is fine now.
Nice job BTW.
I actually use node-red and create sensors from my UDP feed because that doesn’t require cloud but you miss things like “feels_like etc but it is nice for doing things like using the lux value to decide when to turn off/on lights. I was a NodeJS developer in a previous lifetime so I find node-red much easier to work with than Home Assistant. Mostly I use HA for display only but do the heavy lifting in Node-red. 

Thanks for your help.

**Comment by briis** [comment]
Glad you found it😁

If you want to run 100% local, then you could try another thing I made for WeatherFlow, which uses the UDP port. It is called [WeatherFlow 2MQTT](https://github.com/briis/hass-weatherflow2mqtt). This runs as an Add-On if you run the Supervised version of Home Assistant or as a Docker Container, feeding data in to MQTT and creating all the sensors for you. The two Integrations deliver more or less the same sensors.

**Comment by donnievawter** [comment]
That is essentially what I do in node-red. Parse the weather flow UDP data. I have a weather page which uses weewx with belchertown skin. That site is set up to use mqtt. From node-red I publish additional data that weewx doesn’t usually have and I have modified the skin to display it. That part has nothing to do with HA and I use an external mqtt broker for that. I also take the UDP feed and create a  HA sensor. Simpler than yours because it only uses about twenty attributes but the same idea. It does not need mqtt because node-red passes the data directly to the sensor object.

So it sounds like we are pretty much on the same wavelength. I am using NodeJS and you are using python. Two roads to the same destination. Yours is obviously more thorough and better integrated with the HA ecosystem and I will certainly use it for many things.
