### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alexbromberek2020** [briis/hass-weatherflow#26]
I am getting this error

Retrying setup: Error while retreiving data: Timeout fetching weatherflow data. 

and it was working fine like a week ago

**Comment by briis** [comment]
As the message says, it times out when trying to get valid data. Normally this happens when there is something wrong with the data the station provides. Are you sure everything is operational?
If you want I can check the raw data, then just post your Station ID.

**Comment by alexbromberek2020** [comment]
It is 64959

**Comment by alexbromberek2020** [comment]
And yes everything is working

**Comment by briis** [comment]
So this message shows up once in a while, or is it all the time?

**Comment by alexbromberek2020** [comment]
It is working now maybe it is my internet at night because I do have satellite internet because That is all I can get until starlink

**Comment by briis** [comment]
Yes a missing Internet connection, would cause that exact error. The Integration does retry, so when your Internet is back up, it should start pulling data again.
I will close this now.

**Comment by danVnest** [comment]
I am also getting this error:
<img width="281" alt="Screen Shot 2022-01-06 at 8 11 38 am" src="https://user-images.githubusercontent.com/4771860/148290308-9ba9f81b-d650-4c4e-ae5d-809a875a5ae7.png">
But also this in the logs:
<img width="811" alt="Screen Shot 2022-01-06 at 8 08 13 am" src="https://user-images.githubusercontent.com/4771860/148290451-fc2a4c86-316e-413f-b286-00a61e340648.png">

I don't believe there is an issue with the internet connectivity.
I have tried restarts and just leaving it to try and connect for several hours.
Any ideas on how to resolve?

My station: https://url.dev/MeUAobd/

**Comment by briis** [comment]
I just checked your raw data - the reason this is not working is that your tempest device is assigned as an `indoor? environment device, and with that, all data fields are getting the word `_indoor` attached to them. So basically all the data points I check for, are not found as I don't expect field names to be post-fixed with `indoor`.

If it does not matter for you, could you try and change the *Environment* to `outdoor`, and see if it works?

I assume they do this, to be able to distinguish between different stations, but my program is not expecting it - especially not for a Tempest device, as it does not really make sense to put this indoor.

**Comment by danVnest** [comment]
That fixed it - thank you very much @briis.
I must have accidentally toggled it to indoor. It is a rather unusual UI element.

**Comment by briis** [comment]
Perfect. Glad that worked. But I also learned something🤔 It will be rare, but someone might have the older devices and f.ex two AIR units, where one is Indoor. I can not handle that as it is today.

**Comment by imhotep** [comment]
Hello,

I am having this issue as well now:

Logs:
```
2022-01-20 09:47:29 DEBUG (MainThread) [custom_components.weatherflow] Finished fetching weatherflow data in 0.911 seconds (success: False)
2022-01-20 09:47:39 DEBUG (MainThread) [custom_components.weatherflow] Finished fetching weatherflow data in 0.258 seconds (success: False)
2022-01-20 09:48:00 DEBUG (MainThread) [custom_components.weatherflow] Finished fetching weatherflow data in 0.175 seconds (success: False)
```

My station is set to outdoor. I've tried removing the integration and adding it back and I've also tried deleting the token and creating a new one.

My station ID: 34158

**Comment by briis** [comment]
There is something wrong with the Station. The only data returned for your stations is the below, so no Temperature, Humidity and wind data (Plus derived values from these). I recommend you try and restart your Hub, and if that does not work, you will have to restart your Tempest device.

There is nothing I can do about it, as this is a HW issue.

```json
  "obs": [
    {
      "timestamp": 1642701396,
      "precip": 0,
      "precip_accum_last_1hr": 0,
      "precip_accum_local_day": 0,
      "precip_accum_local_day_final": 0,
      "precip_accum_local_yesterday": 0,
      "precip_accum_local_yesterday_final": 0,
      "precip_minutes_local_day": 0,
      "precip_minutes_local_yesterday": 0,
      "precip_minutes_local_yesterday_final": 0,
      "precip_analysis_type_yesterday": 0,
      "lightning_strike_last_epoch": 1640456953,
      "lightning_strike_last_distance": 32,
      "lightning_strike_count": 0,
      "lightning_strike_count_last_1hr": 0,
      "lightning_strike_count_last_3hr": 0,
      "pressure_trend": "unknown"
    }
  ]
````

**Comment by imhotep** [comment]
@briis thanks! You were right. I had to restart the hub and the station. It actually wasn't even reporting in the app.
