### ISSUE TITLE
weatherflow weather not showing up in add integration

### ISSUE THREAD

**Issue by kj4dxk** [briis/hass-weatherflow#30]
I just moved from the old weatherflow to this new weatherflow and I have installed this new one in hacs but I do not see it in add integrations so I cannot finish setting up like adding my personal use token.

**Comment by briis** [comment]
It is a caching issue of the Integrations page
When you are on the Integrations page, do a HARD REFRESH in of your browser, and try and add it again.

**Comment by kj4dxk** [comment]
This fixed it.  I actually just used another computer and it showed up and added in just fine.
