### ISSUE TITLE
Weatherflow Integration Broken For Several Weeks

### ISSUE THREAD

**Issue by Colorado4Wheeler** [briis/hass-weatherflow#32]
For a while my WF integration was working like a charm, but for the past few weeks it's all unavailable, even though the station itself is just fine.  Today I decided to delete the integration and re-add it in case there was something amiss there, but it just made it worse and instead of having unavailable devices, I have none at all.

I don't see anything in the logs, all I have is the integration card:
![image](https://user-images.githubusercontent.com/20329385/158698649-2838f6ec-02d2-455f-93f9-115ae6fe8114.png)

I can ping the API server from HA so it's not a connectivity issue:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/20329385/158698978-c024778c-9855-4488-81ac-bc8082d64423.png">

I'm not sure where to go from here.

**Comment by briis** [comment]
I assume you have fixed the problem, since you closed the issue? But in general, this is caused by the WeatherStation not reporting correctly to WeatherFlow. I can check the raw data, but recommendation is to restart Hub and Tempest device, and things normally work again.

**Comment by Colorado4Wheeler** [comment]
Power cycling the device got it talking to HA again but started having other problems so it's being replaced under warranty, so it may have dropped off again anyway.  Should be resolved once I get the new one.  Thanks :).
