### ISSUE TITLE
home assistant no manifest.json file found custom_components/none/manifest.json

### ISSUE THREAD

**Issue by Trukmeister** [briis/hass-weatherflow#33]
When I try to update from 2.2.10 to 2.2.12 I get this:  home assistant no manifest.json file found custom_components/none/manifest.json

Any ideas how to get past this?
Thanks!

**Comment by briis** [comment]
What Integration are you trying to install? This integration is only at V1.0.4?

**Comment by Trukmeister** [comment]
> Got it. The Integration you are running has been deprecated, and has been replaced by this new Integration. You have to uninstall SmartWeather from the Integrations page, and then go to HACS and search for WeatherFlow. This will then install this new integration, which gives you the same data, but is a more modern Integration.
> 
> Please note, that most of the sensors have gotten new names, so there will be some work on your Ui and in automations.

When I follow these steps below after installing V1.0.4 from HACS:
Go to Configuration and Integrations
Click the + ADD INTEGRATION button in the lower right corner.
Search for WeatherFlow and click the integration.
(The search results for Weatherflow show "Weatherflow - Local" - clicking on that
I get this error:  This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

I am doing this all from HA and not a browser.

Any ideas?  Thanks!

**Comment by briis** [comment]
Start by making sure that you completely removed the old integration. It was called SmartWeather - it has to be removed both from the Integration page and from HACS. Then restart Home Assistant.

The back on the Integrations page, do a hard refresh of your browser to ensure the cash is cleared. Then click the + ADD INTEGRATION button and search for `WeatherFlow Weather`. This can only be configured through the UI, so it should work.

If this does not work, let me know what version of Home Assistant you are using.

**Comment by briis** [comment]
Assuming this is now fixed. Else please reopen with new information.
