### ISSUE TITLE
Feature Request: adding Hail Sensor

### ISSUE THREAD

**Issue by badewanne1234** [briis/hass-weatherflow#35]
Would it be possible to add a Hail sensor? Would be nice to use the hail sensor for the window covers to open / raise to avoid damage.

According to the documentation, hail is supported: https://weatherflow.github.io/Tempest/api/ws.html

FYI: I have also posted this in the same feature request in the [smartweatherudp](https://github.com/briis/smartweatherudp/issues/44) repository.

Thank you!

**Comment by briis** [comment]
This Integration uses the REST API and in that API that data is not available. However if you run Home Assistant in Supervised mode you can use the Add-On I developed for that. This runs completely local, and will give you a field called precipitation type which contains that data.

You can [read more here](https://github.com/briis/hass-weatherflow2mqtt) on how to set that up.
