### ISSUE TITLE
Error while retreiving forecast data: Error occured processing forecast data.

### ISSUE THREAD

**Issue by verstrepeng** [briis/hass-weatherflow#36]
Since yesterday I got following error and data is missing:
`2022-03-26 20:45:47 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Sint-Katelijne-Waver, Molenvelden' for weatherflow integration not ready yet: Error while retreiving forecast data: Error occured processing forecast data. Error message: 'current_conditions'; Retrying in background`

**Comment by briis** [comment]
There is something going wrong when fetching the Forecast Data. Would you mind sharing your station id, then I can check the raw data?

**Comment by briis** [comment]
Assuming this is resolved so closing the issue. Please reopen if that is not the case, with some new information.
