### ISSUE TITLE
Feature request: wind units

### ISSUE THREAD

**Issue by tomlut** [briis/hass-weatherflow#4]
Previous integration had wind speed in km/h new integration is in m/s.

I would actually prefer Knots. 

Is it possible to make this user selectable?

**Comment by briis** [comment]
I can create a new sensor for each wind entity that display values in Knots, and then you can use that instead. This applies to the sensors. The Weather Entities needs fixed units and cannot be changed (km/h and mph)

Would that Work?

**Comment by tomlut** [comment]
That would be great!

**Comment by briis** [comment]
Added in 0.1.9 release.
