### ISSUE TITLE
HA BETA - 2022.7.0b0 - Deprecation Warnings

### ISSUE THREAD

**Issue by jazzyisj** [briis/hass-weatherflow#43]
`2022-06-29 20:53:45 WARNING (MainThread) [homeassistant.components.weather] custom_components.weatherflow.weather::WeatherFlowWeatherEntity is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author.`

**Comment by briis** [comment]
Thanks for reporting this. The fix is done, just waiting for the release version of 2022.7 to release.

**Comment by jwvanderbeck** [comment]
Saw this today.  2022.7 is out right? Pretty sure that is what I upgraded to.  How do we update this component?

**Comment by briis** [comment]
This fix is released as V1.0.6 a few days ago. In my own installation it showed right after I upgraded to the final version of 2022.7.0.
Try and go to HACS and *Redownload* the Integration to see if that helps.

**Comment by jwvanderbeck** [comment]
Thanks I just went to HACS and actually saw it listed an update for this available so that's my bad. I'm new to HACS :)

**Comment by briis** [comment]
No problem. Glad you found it.
