### ISSUE TITLE
HA v2022.11.0 - WARNING Detected integration that accesses the `is_metric` property of the unit system

### ISSUE THREAD

**Issue by jazzyisj** [briis/hass-weatherflow#47]
Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for weatherflow using this method at custom_components/weatherflow/__init__.py, line 72: if hass.config.units.is_metric

**Comment by briis** [comment]
Thanks for reporting. I was already in the process of fixing this. Will be released when 2022.11 is released

**Comment by briis** [comment]
1.0.8 released, which closes this.
