### ISSUE TITLE
Absolute humidity is using an invalid native unit of measurement

### ISSUE THREAD

**Issue by davecpearce** [briis/hass-weatherflow#53]
I am seeing this error message in my logfile:

Entity sensor.weatherflow_absolute_humidity (<class 'custom_components.weatherflow.sensor.WeatherFlowSensor'>) is using native unit of measurement 'g/m^3' which is not a valid unit for the device class ('humidity') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

I am not sure what the best approach is on resolving this.  I believe the HUMIDITY device class needs to be in %.

**Comment by briis** [comment]
It has been fixed. I will release the fix soon.

**Comment by briis** [comment]
Release V1.0.9 where this is fixed.
