### ISSUE TITLE
Setup failed for custom integration weatherflow: Requirements for weatherflow not found: ['pyweatherflowrest==1.0.9'].

### ISSUE THREAD

**Issue by davidcoulson** [briis/hass-weatherflow#54]
After upgrading to 1.0.9 via HACS I get the following startup error in Home Assistant (2023.1.1) - Looks like 1.0.8 is the latest release of pyweatherflowrest, unless I am reading the GitHub repo wrong? 

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 10:15:32 AM (3 occurrences)
Last logged: 10:15:37 AM

Unable to install package pyweatherflowrest==1.0.9: ERROR: Could not find a version that satisfies the requirement pyweatherflowrest==1.0.9 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8) ERROR: No matching distribution found for pyweatherflowrest==1.0.9 [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by tchoward** [comment]
same issue for me

**Comment by briis** [comment]
Sorry, my bad - had accidentally put in the wrong version. Fixed now with V1.0.10
