### ISSUE TITLE
Unit of Measurement Consistency with HA and other Integrations

### ISSUE THREAD

**Issue by mwolter805** [briis/hass-weatherflow#57]
Hello,
Noticed there is a unit_of_measurement inconsistency with other integrations and sensors. This became apparent when attempting to compare measurements from the hass-weatherflow and [Thermal Comfort](https://github.com/dolezsa/thermal_comfort) integrations. 

As you can see in the screenshot below, because the unit_of_measurement is not consistent between the sensors, the scales do not match and the values can not be easily compared. 
![Screenshot 2023-02-10 at 11 27 32 AM](https://user-images.githubusercontent.com/24851651/218180236-a6d2f9ed-7130-4ac6-951f-f769dff9303e.jpg)

In the graph, "Back Patio" is a sensor from hass-weatherflow and uses the unit of measurement "g/m^3" the other two sensors are from Thermal Comfort and use the unit of measurement "g/m³". Note, hass-weatherflow uses the carrot symbol (^) to indicate power when Thermal Comfort uses the cubed symbol. 

In spirit of consistency and compatibility with Home Assistant, when reviewing [these documents](https://developers.home-assistant.io/docs/core/entity/sensor/?_highlight=unit_of_measurement#available-device-classes), it appears all units for area or volume use the cubed (³) or squared (²) symbol and not the carrot symbol (ie ^3, or ^2). 

Although there could be more, it appears there are two sensors created by hass-weatherflow that use carrot.
![Screenshot 2023-02-10 at 11 22 02 AM](https://user-images.githubusercontent.com/24851651/218182904-42cb8754-2d13-4e1c-a65b-4121d39373be.jpg) 

Would it be possible to update the units of sensors created by hass-weatherflow and possibly [hass-weatherflow2mqtt](https://github.com/briis/hass-weatherflow2mqtt) to be more consistent with Home Assistant?

Regards,
Matt

**Comment by briis** [comment]
Fixed with release 1.0.13.

**Comment by mwolter805** [comment]
@briis Looks like an incorrect unit was used. Appears that micro grams per cubic meter (µg/m³) was used instead of grams per cubic meter (g/m³).
![Screenshot 2023-02-11 at 8 39 16 AM](https://user-images.githubusercontent.com/24851651/218269940-4dada2c3-8c1b-4d7b-8632-e022e7307434.jpg)

**Comment by briis** [comment]
Ups - You are right. Fixed with 1.0.14

**Comment by mwolter805** [comment]
perfect, thanks
