### ISSUE TITLE
Weatherflow Hourly based Forecast: Inconnu

### ISSUE THREAD

**Issue by lostcontrol** [briis/hass-weatherflow#65]
As visible in the following screenshot, I sometimes get 'unknown' ('Inconnu' in French) as the current weather condition:

![image](https://user-images.githubusercontent.com/983305/227939511-d86e0a1f-ea4f-4c19-8adb-64db56307126.png)

I get this for a few weeks/months now. Not sure if it was caused by a change in this plugin or if Weatherflow changed something in their API. One of the statuses is probably not mapped properly. I didn't manage to find which one at the moment. Looks also like there is no French translation in this plugin so I guess the value "Inconnu" comes from HA directly.

Looking at the code, I guess you take the value from "icon" in "current_conditions" from [/better_forecast](https://weatherflow.github.io/Tempest/api/swagger/#!/forecast/getBetterForecast). I'll see if I can find the value reported by Weatherflow API when the problem occurs.

There is nothing in HA's logs by the way.

**Comment by briis** [comment]
Yes the value is derived from the icon. When it occurs, try and switch the UI language to English at se what is says then. It might be as simple as a translation key that is missing.

**Comment by lostcontrol** [comment]
Sorry, I should have followed this issue more closely. I haven't seen the issue in the meantime. Maybe it will re-appear during winter. I'll reopen if it pops up again.
