### ISSUE TITLE
Failed to setup 

### ISSUE THREAD

**Issue by evilbobby** [briis/hass-weatherflow#68]
I am running home assistant blue and after upgrading the supervisor and core yesterday I haven't been able to get the weatherflow HACS integration to run. 

integration page shows: "failed to setup" check the logs. 

relevant log message: 

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/weatherflow/__init__.py:167
Integration: WeatherFlow Weather (documentation, issues)
First occurred: 12:47:54 PM (2 occurrences)
Last logged: 12:51:39 PM

Error setting up entry Cliffhouse for weatherflow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/weatherflow/__init__.py", line 167, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, WEATHERFLOW_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

System: 
Home Assistant Blue
HA OS: 10.1
HA Supervisor: 2023.04.1
HA Core: 2023.5.2

**Comment by outbreak04** [comment]
I tried setting this up as well, and received almost the same errlr.
`Logger: homeassistant.config_entries
Source: custom_components/weatherflow/__init__.py:72
Integration: WeatherFlow Weather ([documentation](https://github.com/briis/hass-weatherflow), [issues](https://github.com/briis/hass-weatherflow/issues))
First occurred: May 13, 2023 at 2:31:32 PM (8 occurrences)
Last logged: 5:58:41 AM

    Error setting up entry Home Weather for weatherflow
    Error setting up entry Home for weatherflow

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/weatherflow/__init__.py", line 72, in async_setup_entry
    if hass.config.units.is_metric
AttributeError: 'UnitSystem' object has no attribute 'is_metric'`

**Comment by mlapida** [comment]
I'm getting the same error. This was previously working perfectly, but stopped. Uninstalling/reinstalling does not resolve the issue.

**Comment by JevVan** [comment]
Same here:  Line 387 error.  Tried removing the integration.  Then I upgraded it in HACS and then I set it up again under integrations.  Still no luck.  I may try removing completely from HACS and starting over that way.

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/weatherflow/__init__.py:167
Integration: WeatherFlow Weather (documentation, issues)
First occurred: June 22, 2023 at 2:45:37 PM (5 occurrences)
Last logged: 9:17:54 PM

Error setting up entry myWeatherFlow for weatherflow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherflow/__init__.py", line 167, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, WEATHERFLOW_PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
`

**Comment by notmayo** [comment]
I have just received a new tempest weather station for the first time, I just installed this add-on for the first time, and I was able to install and configure this smoothly on the latest home assistant os, and supervisor. Just some feedback to assist with troubleshooting.

**Comment by ramphex** [comment]
Worked fine for years, now this...
<img width="1010" alt="Screenshot 2023-08-09 at 15 38 49" src="https://github.com/briis/hass-weatherflow/assets/43665314/e3d9e95b-3163-4885-8223-86e33f23149c">

**Comment by drothenberger** [comment]
I am having the same problem setting up this integration for a new Tempest device.

Home Assistant 2023.8.2
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.0 - latest

I see this error in my logs:

`2023-08-17 15:15:36.876 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Kenmore' for weatherflow integration not ready yet: Error while retreiving forecast data: Error occured processing forecast data. Error message: 'uv'; Retrying in background`
