### ISSUE TITLE
Dutch language file

### ISSUE THREAD

**Issue by dhover** [briis/hass-weatherflow#7]
Attached is the Dutch language file.
[nl.json.txt](https://github.com/briis/hass-weatherflow/files/7654753/nl.json.txt)

**Comment by briis** [comment]
Thank you. Could you look at the `sensor.en.json` file also and create a Dutch translation for that?

**Comment by briis** [comment]
Added in 0.1.9 release.

**Comment by dhover** [comment]
Attached the Dutch translation.
[sensor.nl.json.txt](https://github.com/briis/hass-weatherflow/files/7656188/sensor.nl.json.txt)

**Comment by briis** [comment]
Thanks. Will add this in next release.
