### ISSUE TITLE
Home Assistance not finding weatherflow 

### ISSUE THREAD

**Issue by adamsfour** [briis/hass-weatherflow#70]
Installed Raspberry Pi with Home Assistance. Went to appropriate URL, created account. HA discovered multiple items on network but not weatherflow. Tried to add integration but no weatherflow. Tried finding via Add-on still nothing. What am I doing wrong.

**Comment by peteplays** [comment]
☝️ same experience.  Id love to have this integration. 

<img width="531" alt="image" src="https://github.com/briis/hass-weatherflow/assets/5495067/79ed7246-0861-42de-894e-0c9973499644">


<img width="545" alt="image" src="https://github.com/briis/hass-weatherflow/assets/5495067/3ae7d669-11cf-4c7c-a3b2-cae3efefa6c7">

**Comment by peteplays** [comment]
> Did you add the repo through HACS?

@idaband i did not add the repo.  i searched for it in the localhost web app.

do i need to add the repo?

**Comment by idaband** [comment]
Yes, you need to add the repo in hacs first... Then go to setting/devices and search for weatherflow.


If you make it to the point of adding your station id and api key... There is a bug.
Currently they are working a bug.  You can't setup without an error message.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
