### ISSUE TITLE
Fix entity names to avoid duplicate "tempest"

### ISSUE THREAD

**Issue by pcfens** [briis/hass-weatherflow#72]
After upgrading to 2023.8.0 I was met with this message:

Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

- sensor.tempest_pressure_trend
- sensor.tempest_solar_elevation
- sensor.tempest_wind_speed
- sensor.tempest_snow_probability
- sensor.tempest_air_density
- sensor.tempest_rain_today
- sensor.tempest_zambretti_number
- sensor.tempest_lightning_count
- sensor.tempest_dew_point
- sensor.tempest_solar_radiation
- sensor.tempest_sea_level_pressure
- sensor.tempest_precipitation_type
- sensor.tempest_fog_probability
- sensor.tempest_rain_rate
- sensor.tempest_temperature
- sensor.tempest_station_pressure
- sensor.tempest_lightning_count_today
- sensor.tempest_lightning_distance
- sensor.tempest_last_lightning_strike
- sensor.tempest_dewpoint_comfort_level
- sensor.tempest_rain_duration_yesterday
- sensor.tempest_temperature_level
- sensor.tempest_wind_speed_avg
- sensor.tempest_wind_gust
- sensor.tempest_uv_index
- sensor.hub_hb_00123976_weather
- sensor.tempest_cloud_base_altitude
- sensor.tempest_zambretti_text
- sensor.tempest_uv_level
- sensor.tempest_wet_bulb_globe_temperature
- sensor.tempest_rain_yesterday
- sensor.tempest_illuminance
- sensor.tempest_last_rain_start
- sensor.tempest_lightning_count_last_hour
- sensor.tempest_battery
- sensor.tempest_beaufort_scale
- sensor.tempest_delta_t
- sensor.tempest_freezing_level_altitude
- sensor.tempest_wind_bearing_avg
- sensor.tempest_battery_mode
- sensor.tempest_lightning_energy
- sensor.tempest_wet_bulb_temperature
- sensor.hub_hb_00123976_status
- sensor.tempest_lightning_count_3_hours
- sensor.tempest_wind_bearing
- sensor.tempest_rain_duration_today
- sensor.tempest_visibility
- sensor.tempest_wind_direction
- sensor.tempest_absolute_humidity
- sensor.tempest_wind_lull
- sensor.tempest_voltage
- sensor.tempest_wind_direction_avg
- sensor.tempest_solar_insolation
- sensor.tempest_status
- sensor.tempest_humidity
- sensor.tempest_rain_intensity
- sensor.tempest_feels_like_temperature

It also included the note that "This stops working in version 2024.2.0. Please address before upgrading.", so we have some time to fix this, but it still needs addressing.

**Comment by Colorado4Wheeler** [comment]
@pcfens Everyone got this, it's not related to WeatherFlow, it's an issue with HA that the forums say will be addressed in September and can safely be ignored.  Apparently they did some changes in MQTT regarding the names but have not written the mitigation needed to avoid this message.

**Comment by pcfens** [comment]
That sounds way better than having to patch everything. Thanks for the quick reply.

**Comment by Colorado4Wheeler** [comment]
You were only lucky, I was here to report an issue with the hourly weather being broken for 8.0 :).
