### ISSUE TITLE
Hourly Weather Broke in 8.0

### ISSUE THREAD

**Issue by Colorado4Wheeler** [briis/hass-weatherflow#73]
After upgrading to 2023.8.0 I have noticed that the hourly weather no longer populates/renders properly.  I'm not sure if this is transitory and will go away or if it's something that just plain broke in 8.0.

![image](https://github.com/briis/hass-weatherflow/assets/20329385/9e90d240-acfb-419c-839f-151e08263846)
![image](https://github.com/briis/hass-weatherflow/assets/20329385/50b606d3-047c-47b4-af29-4395803b8d07)

**Comment by JGKarlin** [comment]
Same here.

**Comment by lukebrannon1** [comment]
Same for me.

**Comment by Colorado4Wheeler** [comment]
This seems to be with HA and not the plugin (or perhaps a change to HA that multiple extensions have not implemented) because I also see it in my National Weather Service hourly as well:

![image](https://github.com/briis/hass-weatherflow/assets/20329385/4e4b9bc7-302f-45b4-b310-b294e0dea607)

**Comment by Colorado4Wheeler** [comment]
Reported on HA Core: https://github.com/home-assistant/core/issues/97787
