### ISSUE TITLE
Unexpected error fetching weatherflow data: an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by Severinius-MUC** [briis/hass-weatherflow#8]
After installation I got following error (v0.1.9):
My Station ID 63146

Unexpected error fetching weatherflow data: an integer is required (got type NoneType)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/weatherflow/__init__.py", line 104, in async_update_data
    data: ObservationDescription = await weatherflowapi.update_observations()
  File "/usr/local/lib/python3.9/site-packages/pyweatherflowrest/api.py", line 224, in update_observations
    lightning_strike_last_epoch=self.cnv.utc_from_timestamp(
  File "/usr/local/lib/python3.9/site-packages/pyweatherflowrest/helpers.py", line 101, in utc_from_timestamp
    return dt.datetime.utcfromtimestamp(timestamp).replace(tzinfo=UTC)
TypeError: an integer is required (got type NoneType)

**Comment by briis** [comment]
Thank you. It seems that there is some inconsistency in what data is contained for different stations. In your case there is no last time of a Lightning Strike. It might be because the station is relatively new.
I have now changed some things to ensure the program does not crash because of this. Will be out soon with a new update.

**Comment by Severinius-MUC** [comment]
Thank you for the fast reply…yes the station is pretty new. So waiting for the fix.

Thanks in advance

Severinius
Am 5. Dez. 2021, 16:55 +0100 schrieb Bjarne Riis ***@***.***>:

**Comment by briis** [comment]
You can test manually now if you want.

- In your Home Assistant, activate a file editor and edit the file `custom_components/weatherflow/manifest.json`
- search for `pyweatherflowrest==0.1.12` and change this to `pyweatherflowrest==0.1.13`
- restart home assistant, and let me know if this fixes your issue.

**Comment by briis** [comment]
I released 0.1.10 where this is contained. Reopen issue if it still not works.

**Comment by Severinius-MUC** [comment]
Thank you for the fix. Manually updated and now on latest HACS Version.

👍

Regards,
Severinius
Am 5. Dez. 2021, 18:31 +0100 schrieb Bjarne Riis ***@***.***>:
