### ISSUE TITLE
Error on integration page: Failed setup, will retry

### ISSUE THREAD

**Issue by mwoods329** [briis/hass-weatherflow#86]
Even though I've had it running and working fine for quite a while, I noticed yesterday that I wasn't getting any data from my station.  It was all "unavailable".
Looking into the config page, I noticed an error "Failed setup, will retry".
When I hover over that message it says "Error while retrieving forecast data: Error occurred processing forecast data. Error message: sea_level_pressure' "

I've tried reloading, deleting and re-adding, and restarting HASS.
![image](https://github.com/briis/hass-weatherflow/assets/9289668/8b1aa891-a379-4737-9a13-d4c4f7861a2a)

**Comment by PYehl73** [comment]
make sure you are pulling the newest 1.0.16 - that has fixed the sea level pressure issue.
