### ISSUE TITLE
2023.10 Core Integration and Hass-weatherflow using same domain

### ISSUE THREAD

**Issue by notmayo** [briis/hass-weatherflow#88]
I've seen you're already aware they're using the same domain you're using, and now this creates a conflict. Creating this issue just for your visibility. Not possible to have both installed currently.

**Comment by briis** [comment]
I am aware. I am currently developing a new version of this integration with a different domain name. See [`weatherflow_forecast`](https://github.com/briis/weatherflow_forecast).
Currently this only supports the Forecast part, but I will add the sensors later as an option.

**Comment by Notrial** [comment]
Is there a reason for using one over the other, apart from the new one being an "official" one?
I've been using yours for years without any issues btw.

**Comment by briis** [comment]
The 'core' integration uses a different API than this integration. It uses the UDP API, which gives totally local data, so no internet connection required.
This integration uses the REST API, which pulls data from the WeatherFlow Cloud. 

The UDP API, has only the raw sensor data but they are local and fast - the REST API, must access the cloud, but then there is more sensors like feels like temperature, heat index, etc as some of these value requires the value from other sensors.

Please note: To use the new integration you will have to de-install this integration, also from HACS.
