### ISSUE TITLE
Updating state duration

### ISSUE THREAD

**Issue by tyler78** [briis/hass-weatherflow#89]
Not causing me any issues, but per your request.... Here's a log entry I encountered.  Let me know if you need any other information.

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:885
First occurred: 8:32:20 AM (1 occurrences)
Last logged: 8:32:20 AM
Updating state for sensor.weatherflow_battery_tempest (<class 'custom_components.weatherflow.sensor.WeatherFlowSensor'>) took 0.731 seconds. Please create a bug report at https://github.com/briis/hass-weatherflow/issues

**Comment by briis** [comment]
Thanks. However this integration is being deprecated, due to the new WeatherFlow integration introduced in core Home Assistant. Please see the README file, on how to proceed.
