### ISSUE TITLE
correct units but incorrect values?

### ISSUE THREAD

**Issue by jsermer** [briis/hass-weatherflow#9]
I have both integrations installed side by side and they both reflect F (for temp units), but the new integration shows incorrect values.  For example, current temp on the old one shows 37 degrees, but the new one shows 99 degrees.

![image](https://user-images.githubusercontent.com/7101556/144765454-96052b62-f80f-49ec-ba87-1bc83afa3f1b.png)

vs

![image](https://user-images.githubusercontent.com/7101556/144765464-d00da06b-e382-40e1-81bc-e69584b1ac1f.png)

**Comment by jsermer** [comment]
I haven't read thru the code just yet, but i did a quick curl against the api and see even though my device reports units of F, the units are still emitted in C:

```
at 17:47:13 ❯ curl -s https://swd.weatherflow.com/swd/rest/observations/station/ID?token=TOKEN | jq -r '.station_units.units_temp,.obs[0].air_temperature'
f
3.9
```

**Comment by CommittotheIndian** [comment]
I'm seeing the same issue. I just updated to 1.10 today and my temps are off but don't convert from F to C. 

It is currently 57F which should convert to 13.8 but the integration is showing 134.1F. 

![image](https://user-images.githubusercontent.com/60204668/144771067-1184d84e-4761-44f5-9600-7f1befa2c0da.png)

**Comment by jonathanjmakela** [comment]
Same issue. It appears to assume the value read in is in C and then is converting to F (@CommittotheIndian , 57 C converts to 134 F). In sensor.py, it seems to hard code all of the temperature units to TEMP_CELSIUS.

**Comment by briis** [comment]
Thanks. Will be fixed in a few hours. Made a change in one place, and forgot to reflect this in another place.

**Comment by briis** [comment]
V0.1.11 is now released which fixes this issue. I will close this now, please re-open if you still see issues.
